# -*- coding: utf-8 -*-
"""
Created on Mon Dec 12 14:10:19 2022

@author: mml
"""
#%% Imports

import pandas as pd
import numpy as np
import glob
import os
import cv2
from keras.models import model_from_json
import tensorflow as tf
##%% noaa additions
import os
import traceback
import pathlib
import datetime
import csv
import traceback
import PIL
import scipy
import gc

#%choose GPU

#%% choose a gpu
os.environ["CUDA_VISIBLE_DEVICES"]="0"
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))


##%% Path configuration

current_dir = os.path.abspath("Z:\\Processing")
#current_dir = os.path.abspath("Y:\\NMML_CAEP_Acoustics\\DOS_CIBAS\\_Automated_Processing\\2022_retraining")
data_dir = os.path.join(current_dir, "Data")
spectrogram_dir = os.path.join(data_dir,"Validation_Spectrograms")
model_dir = os.path.join(current_dir,"Model")
output_dir = os.path.join(current_dir, "Output")


for i in [output_dir]:

    if not os.path.exists(i):
        os.makedirs(i)

#we need to specify the "training set name" we want to work with
#e.g. BS1KHZ-n721-x1_BDB-n29859-x1
#for replicability's sake, we will store this in a dict

b_positive_variant_dict = {1:"BS1KHZ-n721-x1_BDB-n29859-x1"}
b_false_variant_dict = {1: "FML237-n157-x1_FS1KHZ-n76-x1_FDB-n9860-x1"}
b_negative_variant_dict = {1: "N-n40673-x1"}

#here you can change which variant you are using
positive_variant = 1
false_variant = 1
negative_variant = 1
model_name = "B{b_var}-F{f_var}-N{n_var}".format(b_var = str(positive_variant), f_var = str(false_variant), n_var = str(negative_variant))
print(model_name)

##%% Get Spectrograms from Dataframe based on CSV generated by NOAA spectrogram 
print('loading inference manifest...')
#path_to_file = r"Z:\processing\Data\spectrogram_manifest_to_score_dir\2023-02-14-1534_301.csv"
path_to_file = r"Z:\processing\Data\spectrogram_manifest_to_score_dir\2023-02-06-1955_spectrogram_manifest_306.csv"
full_analysis_score_df = pd.read_csv(path_to_file)

print('done loading inference manifest!')

##%%
deployment = "306_postensemble"#os.path.basename(path_to_file).split("_")[1]
print("You are processing %s" % deployment)

inference_log_filename = "-".join(["inference_log",str(deployment),".csv"])
inference_log_path = os.path.join(output_dir, inference_log_filename)



if os.path.exists(inference_log_path):
    print("file exists...load past work!")
    inference_log = pd.read_csv(inference_log_path)
else:
    print('inference log missing, generate it')
    #get a slice of the old df, just the spectrogram file names
    #create the attribute processed, set as False
    inference_log = full_analysis_score_df[['spectrogram_file_path']]
    inference_log['processed'] = ""
    inference_log['predicted_probability'] = 0.0 #float

#inference_log = pd.read_csv(inference_log_path)

#try:
#    del full_analysis_score_df
#except:
#    pass
total_n_spectrograms = len(inference_log['spectrogram_file_path'])
print("Total number of Spectrograms: ", total_n_spectrograms)




opt_weights = pd.read_excel(os.path.join(output_dir, 
                                         "-".join([model_name, 'opt_weights.xlsx'])), 
                                         header = None)[0].values.tolist()

# flow from directory
# spectrogram_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1.0/255.0, 
#                                                                   data_format = "channels_last")
# spectrogram_generator = spectrogram_gen.flow_from_directory(
#     r"Z:\processing\Data",
#     target_size=(300,300),
#     classes=['Validation_Spectrograms'],
#     color_mode='rgb',
#     shuffle=False, 
#     batch_size = 64
#     )

#% flow from dataframe

def rgb_to_bgr(image):
    "converts input image from rgb to bgr channel order"
    image = np.array(image)
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    
    return image

def bgr_to_rgb(image):
    image = np.array(image)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
    return image

print('generating data with imagedatagenerator...please wait')
spectrogram_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255., 
                                                                  preprocessing_function=rgb_to_bgr)
print('done')

print('preparing flow from df', datetime.datetime.now().strftime("%Y-%m-%d_%H%M"))
spectrogram_generator = spectrogram_gen.flow_from_dataframe(
    dataframe=inference_log, 
    x_col='spectrogram_file_path',                                           
    y_col=None,
    class_mode=None, 
    shuffle=False,
    target_size=(300,300), 
    batch_size = 128)
print('done', datetime.datetime.now().strftime("%Y-%m-%d_%H%M"))



print('starting predictions!')



def perform_inference(friendly_name, model_architecture_json, model_weights_h5, spec_generator_obj):
    print('\nloading {}'.format(friendly_name))
    with open(os.path.join(model_dir, "-".join([model_name,model_architecture_json])), 'r') as f:
        model = model_from_json(f.read())
    model.load_weights(os.path.join(model_dir,"-".join([model_name, model_weights_h5])))
    print("done loading {}".format(friendly_name))
    
    predict_start_time = datetime.datetime.now()
    print("\npredicting with {}".format(friendly_name), predict_start_time)
    model_prediction = model.predict(spec_generator_obj, verbose=1)
    #model_cnn_prediction = model_cnn.predict_generator(spectrogram_generator, verbose=1)
    elasped = datetime.datetime.now() - predict_start_time
    
    print('done, took {} minutes'.format(str(elasped.total_seconds()/60)))
    print('unloading {}'.format(friendly_name))
    
    del model
    gc.collect()
    tf.keras.backend.clear_session()
    
    return model_prediction

##%%
model_cnn_prediction = perform_inference("CNN",'cnn_architecture_all_data.json', 'cnn_weights_all_data.h5', spectrogram_generator)
model_vgg16_prediction = perform_inference("VGG16", 'vgg16_architecture_all_data.json', "vgg16_weights_all_data.h5", spectrogram_generator )
model_ResNet50_prediction = perform_inference("Resnet", 'ResNet50_architecture_all_data.json', 'ResNet50_weights_all_data.h5', spectrogram_generator)
model_DenseNet121_prediction = perform_inference("DenseNet121", 'DenseNet121_architecture_all_data.json', 'DenseNet121_weights_all_data.h5', spectrogram_generator)



##%% output data for directory
results = pd.DataFrame({"spectrogram_file_path":spectrogram_generator.filenames, 
                        "cnn_prediction": model_cnn_prediction.flatten(),
                        "vgg16_prediction": model_vgg16_prediction.flatten(),
                        "resnet50_prediction": model_ResNet50_prediction.flatten(),
                        "densenet121_prediction": model_DenseNet121_prediction.flatten(),
                        
                        })

results['postensemble_score'] = sum([x*y for x,y in zip([results['cnn_prediction'], 
                                                  results['vgg16_prediction'], 
                                                  results['resnet50_prediction'], 
                                                  results['densenet121_prediction']], opt_weights)])

inference_save_time = datetime.datetime.now().strftime("%Y-%m-%d_%H%M")

##%% combine inference log with original to get format
output_df = pd.merge(full_analysis_score_df, results, on="spectrogram_file_path")

##%% shouldn't be necessary

output_df['time_spectrogram_start_relative'] = pd.to_timedelta(output_df['time_spectrogram_start_relative']).dt.total_seconds()
output_df['time_spectrogram_end_relative'] = pd.to_timedelta(output_df['time_spectrogram_end_relative']).dt.total_seconds()


##%% save to file

output_df.to_csv(os.path.join(output_dir,"_".join([inference_save_time, deployment, model_name+".csv"])), index=False, float_format="%.15f")
print("Done {}".format(inference_save_time))