# -*- coding: utf-8 -*-
"""
Created on Mon Dec 12 14:10:19 2022

@author: mml
"""
#%% Imports

import pandas as pd
import numpy as np
import glob
import os
import cv2
from keras.models import model_from_json
import tensorflow as tf
#%% noaa additions
import os
import traceback
import pathlib
import datetime
import csv
import traceback
import PIL
import scipy
import gc
import wave
import pylab
import glob
import os
import wave
import pylab
from matplotlib import pyplot
from joblib import Parallel, delayed  
import multiprocessing
import gc
import shutil



#%% Path configuration

current_dir = os.path.abspath("Z:\\Processing")
#current_dir = os.path.abspath("Y:\\NMML_CAEP_Acoustics\\DOS_CIBAS\\_Automated_Processing\\2022_retraining")
data_dir = os.path.join(current_dir, "Data")
spectrogram_dir = os.path.join(data_dir,"Validation_Spectrograms")
model_dir = os.path.join(current_dir,"Model")
output_dir = os.path.join(current_dir, "Output")

deployment = input('type in your deployment:\n')
output_spectrogram_dir = os.path.join(data_dir, "Extracted_Spectrogram_Full_Analysis", deployment)
remade_spectrogram_dir = os.path.join(data_dir, "Extracted_Spectrogram_Full_Analysis","_".join([deployment,"remade"]))
bad_spectrogram_dir = os.path.join(data_dir, "Extracted_Spectrogram_Full_Analysis","_".join([deployment,"bad"]))


effort_dir = os.path.join(data_dir, "Effort")

for i in [output_dir,remade_spectrogram_dir, bad_spectrogram_dir]:

    if not os.path.exists(i):
        os.makedirs(i)

#we need to specify the "training set name" we want to work with
#e.g. BS1KHZ-n721-x1_BDB-n29859-x1
#for replicability's sake, we will store this in a dict

b_positive_variant_dict = {1:"BS1KHZ-n721-x1_BDB-n29859-x1"}
b_false_variant_dict = {1: "FML237-n157-x1_FS1KHZ-n76-x1_FDB-n9860-x1"}
b_negative_variant_dict = {1: "N-n40673-x1"}

#here you can change which variant you are using
positive_variant = 1
false_variant = 1
negative_variant = 1
model_name = "B{b_var}-F{f_var}-N{n_var}".format(b_var = str(positive_variant), f_var = str(false_variant), n_var = str(negative_variant))
print(model_name)

#%% Get Spectrograms from Dataframe based on CSV generated by NOAA spectrogram 
print('loading inference manifest...')
path_to_file = r"Z:\processing\Data\spectrogram_manifest_to_score_dir\2023-02-14-1534_301.csv"
#path_to_file = r"Z:\processing\Data\spectrogram_manifest_to_score_dir\2023-02-14-1356_305.csv"
full_analysis_score_df = pd.read_csv(path_to_file)

print('done loading inference manifest!')


#%% get effort table

effort_table = pd.read_csv(os.path.join(effort_dir, "CIBA_3_Effort.csv")).set_index(('Deploy ID'))
#effort_table['Effort Start file (UTC)'] = effort_table['Effort Start file (UTC)'].astype('int64')
#effort_table['Effort End file (UTC)'] = effort_table['Effort End file (UTC)'].astype('int64')
current_deployment = effort_table.loc[int(deployment)]

audio_dir = current_deployment[6]#os.path.join(data_dir, "Raw_Audio_Full_Analysis")


effort_start = int("".join(["20", str(int(current_deployment[2]))]))
effort_end = int("".join(["20", str(int(current_deployment[4]))]))

effort_start = pd.to_datetime(effort_start, format=("%Y%m%d%H%M%S"))#.to_datetime64()
effort_end = pd.to_datetime(effort_end, format=("%Y%m%d%H%M%S"))#.to_datetime64()
print(current_deployment)


#%%Functions
def get_wav_info(audio_filename):
    wav = wave.open(audio_filename, 'r')
    frames = wav.readframes(-1)
    sound_info = pylab.frombuffer(frames, 'int16')
    frame_rate = wav.getframerate()
    wav.close()
    return sound_info, frame_rate

def graph_specific_spectrogram(start, end, audio_filename):
    sound_info, frame_rate = get_wav_info(audio_filename)
    audio_length_second = int(len(sound_info) / frame_rate)
    file_basename = os.path.basename(audio_filename)
    
    
    output_file_name = os.path.join(remade_spectrogram_dir, "_".join([file_basename.replace('.wav',""),str(start), str(end)])+'.png')
    

    pyplot.figure(num=None, figsize=(19, 12))
    pyplot.subplot(222)
    ax = pyplot.axes()
    ax.set_axis_off()
    pyplot.specgram(sound_info[frame_rate * start: frame_rate * end], Fs = frame_rate, NFFT=256)
    
    
    print(output_file_name)

    pyplot.savefig(output_file_name, bbox_inches='tight', transparent=True, pad_inches=0.0)
        
    pyplot.close()
    #print('generated %s' % os.path.join(output_spectrogram_dir, 
    #                            "-".join([file_basename,"_".join([file_basename.replace('.wav',""),str(j), str(j + spectrogram_second_length)])])+'.png'))
    gc.collect()

def check_generate_spectrograms(i):
    spectrogram_file_path = full_analysis_score_df['spectrogram_file_path'][i]
    print(i)
    
    try:
        img = PIL.Image.open(spectrogram_file_path)
        img.verify()
    except:
        #move the broken spectrogram
        print("error with {}".format(spectrogram_file_path))
        shutil.move(spectrogram_file_path, os.path.join(bad_spectrogram_dir,os.path.basename(spectrogram_file_path)))
        #try to remake the bad spectrogram
        audio_filename = os.path.join(audio_dir,full_analysis_score_df['wave_filename'][i])
        spectrogram_seconds = os.path.splitext(full_analysis_score_df['spectrogram_file_path'][i])[0].split("_")[-2:]
        start_s = int(spectrogram_seconds[0])
        end_s = int(spectrogram_seconds[1])
        try:
            return graph_specific_spectrogram(start_s, end_s, audio_filename)
        except:
            traceback.print_exc()

#%% Generate Spectrograms
print('Checking Spectrograms')
num_cores = multiprocessing.cpu_count()
num_cores_to_use = int(num_cores)
spectrograms = Parallel(n_jobs=num_cores_to_use)(delayed(check_generate_spectrograms)(i) for i in range(len(full_analysis_score_df)))
print('Done Checking/Generating Spectrograms')